### ISSUE TITLE
Send Invoice after Creating

### ISSUE THREAD

**Issue by Jaspur** [TriPSs/Moneybird-API#2]
Hi @TriPSs,

How to send the invoice after creating it? 

I tried: 
```
$moneybirdInvoice = $moneybirdClient->salesInvoices->create($nInvoice);
$moneybirdClient->salesInvoices->send($nInvoice);
```

**Comment by TriPSs** [comment]
Hi @Jaspur:

Can you try to send the `$moneybirdInvoice` instead of `$nInvoice`:
```
$moneybirdClient->salesInvoices->send($moneybirdInvoice);
```

**Comment by Jaspur** [comment]
Hi @TriPSs, 
That's a quick reply :-) Just tried it and that's also not working.

**Comment by TriPSs** [comment]
Do you get any logs / response from `$moneybirdClient->salesInvoices->send($moneybirdInvoice);`? 

And could you check with `$moneybirdClient->getLastHttpResponseStatusCode()` what the last code returned by Moneybird is?

And if possible can you share a little more of your setup code?

**Comment by TriPSs** [comment]
And is the invoice created with `$moneybirdClient->salesInvoices->create($nInvoice);`?

**Comment by Jaspur** [comment]
Found a response: ```  Error executing API call: Sales Invoice Sending isn't a hash.```

**Comment by Jaspur** [comment]
@TriPSs got an answer from Moneybird about this and they say:

> Bedankt voor je bericht. Als je deze foutmelding krijgt, dan geef je de parameters niet in het goede formaat mee. Je kunt hier nalezen op in welk formaat je ze mee kunt geven aan je request: https://developer.moneybird.com/api/sales_invoices/#patch_sales_invoices_id_send_invoice

You have a clue what to do?

**Comment by TriPSs** [comment]
Hi @Jaspur, I will see if I can repreduce the error as I do not use this project somewhere anymore I will need to setup something.

**Comment by TriPSs** [comment]
Hi @Jaspur, i committed a couple of changes, the following way now works again:
```
$salesInvoice = $moneybirdClient->salesInvoices->send("INVOICE ID");
```
The default send method of the contact is used, to overwrite use the below, that was a way that already worked:

```
$invoiceContact = new \Moneybird\Object\Contact();
$invoiceContact->id = "CONTACT ID";
$invoiceContact->delivery_method = "Email";
$invoiceContact->email = "your@email.com";

$salesInvoice = $moneybirdClient->salesInvoices->setContact($invoiceContact);
$salesInvoice->send("INVOICE ID");
```

**Comment by Jaspur** [comment]
@TriPSs  thanks, but it's still not working:

```
public function createInvoice(float $price)
{
    $moneybirdClient     = $this->init(); // working
    $nInvoice            = new MoneybirdSalesInvoice();

    $productOne              = new MoneybirdDetail();
    $productOne->description = "Foobar";
    $productOne->price       = 120;
    $nInvoice->addDetail($productOne);

    $nInvoice->addContact(auth()->user()->moneybird_contact_id);

    $moneybirdInvoice = $moneybirdClient->salesInvoices->create($nInvoice);
    $salesInvoice = $moneybirdClient->salesInvoices->send($moneybirdInvoice->id);    }
    return $moneybirdInvoice;
}

In ResourceBase.php line 211:

  Invalid argument supplied for foreach()

```

**Comment by Jaspur** [comment]
@TriPSs thanks, it's working now!
