### ISSUE TITLE
Object of class stdClass could not be converted to string

### ISSUE THREAD

**Issue by Jaspur** [TriPSs/Moneybird-API#3]
Hi, since last update I'm getting this:
![unspecified](https://user-images.githubusercontent.com/4254854/48710305-25a0f880-ec08-11e8-998e-3dcd4a92dac7.png)

**Comment by TriPSs** [comment]
Hi, can you `print_r` || `var_dump` the object?

**Comment by Jaspur** [comment]
It occurs when creating a Contact with delivery_method inside it that you showed at #2 
```
{#1418 ▼
  +"error": {#1415 ▼
    +"delivery_method": array:1 [▼
      0 => "is not a valid value"
    ]
  }
}
```

**Comment by TriPSs** [comment]
Hmm, looks like they changed the errors.

Can you show me the code that is causing this error for you?

**Comment by Jaspur** [comment]
https://github.com/TriPSs/Moneybird-API/issues/2#issuecomment-439847919 > happens when added delivery_method. works fine without.

**Comment by TriPSs** [comment]
@Jaspur still would like to solve this, the code that i pasted in the comment that did not work for you? It should also work with but they are very specific in the value, it is it is case-sensitive
